import { getThemeColor } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#000' },
    unavailable: { alignItems: 'center', justifyContent: 'center', gap: 12, paddingHorizontal: 32 },
    closeBtn: { position: 'absolute', left: 20, zIndex: 10 },
    recordingPill: {
        position: 'absolute',
        alignSelf: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        backgroundColor: 'rgba(255,255,255,0.08)',
    },
    recordingDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: getThemeColor('tint'),
    },
    recordingDotPaused: { backgroundColor: getThemeColor('textSecondary') },
    recordingText: { color: '#fff', fontSize: 13, fontWeight: '600' },
    info: {
        position: 'absolute',
        left: 32,
        right: 32,
        alignItems: 'center',
        gap: 8,
    },
    title: {
        color: '#fff',
        fontSize: 20,
        fontWeight: '700',
        textAlign: 'center',
    },
    subtitle: {
        color: getThemeColor('textSecondary'),
        fontSize: 15,
        textAlign: 'center',
        lineHeight: 20,
    },
    spinner: { marginTop: 8 },
    actions: {
        position: 'absolute',
        left: 24,
        right: 24,
        bottom: 0,
        gap: 4,
    },
    primaryBtn: {
        backgroundColor: getThemeColor('tint'),
        paddingVertical: 14,
        borderRadius: 25,
        alignItems: 'center',
    },
    primaryText: { color: '#fff', fontSize: 16, fontWeight: '600' },
    secondaryBtn: { paddingVertical: 14, alignItems: 'center' },
    secondaryText: { color: '#fff', fontSize: 16, fontWeight: '500' },

    consent: { paddingHorizontal: 24, justifyContent: 'space-between' },
    consentBody: { alignItems: 'center', gap: 12 },
    consentIcon: {
        width: 84,
        height: 84,
        borderRadius: 42,
        backgroundColor: 'rgba(255,255,255,0.06)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    consentPoints: { alignSelf: 'stretch', gap: 18, marginTop: 20 },
    consentPoint: { flexDirection: 'row', alignItems: 'center', gap: 16 },
    consentPointText: { flex: 1, color: '#fff', fontSize: 15, lineHeight: 20 },
    consentActions: { gap: 4 },
    consentFootnote: {
        color: getThemeColor('textSecondary'),
        fontSize: 12,
        lineHeight: 16,
        textAlign: 'center',
        marginBottom: 12,
    },
});
